name: Deploy Backend to AWS EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Zipar arquivos
        run: zip -r output.zip src node_modules package.json package-lock.json

      - name: Upload de artefatos da Lambda
        uses: actions/upload-artifact@v4
        with:
          name: lambda_package
          path: lambda_package.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Baixar Artefatos
        uses: actions/download-artifact@v4
        with:
          name: lambda_package
      - name: Deploy lambda Zip
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: fastfood-auth-lambda
          zip_file: lambda_package.zip
          dry_run: true
